### ISSUE TITLE
Object rotate after new Document

### ISSUE THREAD

**Issue by MichaelKoch** [methodofaction/Method-Draw#34] opened 2015-07-22 09:57 UTC
Hi ,
the Editor has Problems to rotate ( i.e. circle)  elements after 
create New Document .

To reproduce:

http://editor.method.ac/
     --> Draw Circle 
      --> Menu --> File --> New Document 
     --> Draw Circle 
     --> Try to rotate 
I would be happy if this bug will be fixed . 

kind regards

Michael

**Comment by duopixel** [comment] 2015-07-22 15:21
Acknowledged, can't say when this will be fixed but I'll take a look soon.

**Comment by nicholaswmin** [comment] 2017-11-08 06:46
@MichaelKoch Can you still reproduce this?

**Comment by methodofaction** [comment] 2020-08-02 11:31
Can't reproduce anymore

**Closed by methodofaction** 2020-08-02 11:31 UTC
